### ISSUE TITLE
Hook up the logic to swipe postings

### ISSUE THREAD

**Issue by chriswill21** [FBU-2018/Jumble#2]
- Someone should be able to swipe up to try and match with a job, down to dismiss a job
- Posting object in parse should have the user that swiped in a "attempted match" column
- Some notification/animation notifying the user that the app has acknowledged the swipe as a "try to match" or "dismiss"

**Comment by kimberlylo** [comment]
Right swipe implemented in FeedFragment.java.

**Comment by kimberlylo** [comment]
Completed in FeedFragment.java.
